apiVersion: v1
kind: ConfigMap
metadata:
  name: loudkeeper-config
  namespace: loudkeeper
data:
  PORT: "8080"
  NODE_ENV: production
  ENVIRONMENT: staging
  SERVE_CLIENT_FROM_NEST: "true"
  CLIENT_PATH: /app/client
  API_BASE_URL: https://app.loudkeeper.ai/api
  FRONTEND_URL: https://app.loudkeeper.ai
  WS_BASE_URL: https://app.loudkeeper.ai
  SENTRY_ENVIRONMENT_TAG: staging
  JWT_EXPIRES: 365d
  DATABASE_HOST: loudkeeper-postgres-rw
  DATABASE_NAME: loudkeeper
  DATABASE_USER: loudkeeper
  DATABASE_PORT: "5432"
  DATABASE_SSL: "false"
  DATABASE_MAX_CONNECTIONS: "50"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  POSTHOG_MESSAGE_COUNT: "false"
  CLICKHOUSE_HOST: clickhouse:8123
  CLICKHOUSE_USER: loudkeeper
  CLICKHOUSE_DB: default
  CH_MIGRATIONS_HOST: clickhouse
  CH_MIGRATIONS_USER: loudkeeper
  CH_MIGRATIONS_PORT: "8123"
  CH_MIGRATIONS_DB: default
  CH_MIGRATIONS_HOME: /app/packages/server/src/migrations/clickhouse
