apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - config.yaml
  - rabbitmq.yaml
  - postgresql.yaml
  - clickhouse.yaml
  - deployment.yaml
  - ingress.yaml

images:
  - name: ghcr.io/helpin-labs/loudkeeper
    newTag: stage-latest
