name: Build, test, and deploy on commit
on:
  push:
    branches:
      - production
      - staging
permissions:
  contents: read
  packages: write
jobs:
  setup:
    name: Setup variables
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.params.outputs.short_sha }}
      env: ${{ steps.params.outputs.env }}
      external_url: ${{ steps.params.outputs.external_url }}
    steps:
      - id: params
        run: |
          SHA=${{ github.sha }}
          echo short_sha=${SHA:0:20} >> "$GITHUB_OUTPUT"
          BRANCH=${{ github.ref_name }}
          if [[ $BRANCH == "staging" ]]; then
            echo env=staging >> "$GITHUB_OUTPUT"
            echo external_url=staging-app.laudspeaker.com >> "$GITHUB_OUTPUT"
          fi
          if [[ $BRANCH == "production" ]]; then
            echo env=prod >> "$GITHUB_OUTPUT"
            echo external_url=app.laudspeaker.com >> "$GITHUB_OUTPUT"
          fi

  build:
    needs: [setup]
    name: Build docker image
    uses: ./.github/workflows/build.yml
    with:
      dockerfile: Dockerfile
      output: laudspeaker
      external_url: ${{ needs.setup.outputs.external_url }}
      publish: true
      tags: |
        ghcr.io/helpin-labs/loudkeeper:${{ needs.setup.outputs.short_sha }}
        ${{ github.ref_name == 'staging' && 'ghcr.io/helpin-labs/loudkeeper:latest' || '' }}
  test:
    needs: [setup, build]
    name: Test docker image
    uses: ./.github/workflows/test.yml
    with:
      image: laudspeaker
  deploy:
    needs: [setup, build, test]
    name: Redeploy staging
    uses: ./.github/workflows/deploy.yml
    with:
      image-repository: ghcr.io/helpin-labs/loudkeeper
      image-tag: ${{ needs.setup.outputs.short_sha }}
      env: ${{ needs.setup.outputs.env }}
    secrets: inherit
